services:
  mousse.api:
    image: ${DOCKER_REGISTRY-}mousseapi
    build:
      context: src/mousse.Api
      dockerfile: Dockerfile
    ports:
      - 5000:8080
      - 5001:8081

  mousse.keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: mousse.keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://mousse.keycloak-database:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    depends_on:
      - mousse.keycloak-database
    ports:
      - 8080:8080
 
  mousse.keycloak-database:
    image: postgres:latest
    container_name: mousse.keycloak-database
    volumes:
      - ./.containers/keycloak-database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5433

  mousse.database:
    image: postgres:latest
    container_name: mousse.database
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mousse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432