// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using mousse.Persistence;

#nullable disable

namespace mousse.Persistence.Migrations
{
    [DbContext(typeof(MousseContext))]
    [Migration("20240722210100_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlaylistTrack", b =>
                {
                    b.Property<Guid>("PlaylistsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TracksId")
                        .HasColumnType("uuid");

                    b.HasKey("PlaylistsId", "TracksId");

                    b.HasIndex("TracksId");

                    b.ToTable("PlaylistTrack");
                });

            modelBuilder.Entity("TagTrack", b =>
                {
                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid");

                    b.HasKey("TagsId", "TrackId");

                    b.HasIndex("TrackId");

                    b.ToTable("TagTrack");
                });

            modelBuilder.Entity("mousse.Domain.Accesses.Access", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "PlaylistId");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("UserId", "PlaylistId");

                    b.ToTable("Accesses");
                });

            modelBuilder.Entity("mousse.Domain.Followers.Follower", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FollowedId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "FollowedId");

                    b.HasIndex("FollowedId", "UserId");

                    b.ToTable("Followers");
                });

            modelBuilder.Entity("mousse.Domain.Playlists.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<int>("PlaylistType")
                        .HasColumnType("integer");

                    b.ComplexProperty<Dictionary<string, object>>("PlaylistName", "mousse.Domain.Playlists.Playlist.PlaylistName#PlaylistName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("PlaylistName");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("Id");

                    b.ToTable("Playlists");

                    b.HasDiscriminator<int>("PlaylistType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("mousse.Domain.Playlists.Tracks.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("Duration", "mousse.Domain.Playlists.Tracks.Track.Duration#Duration", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Seconds")
                                .HasColumnType("integer")
                                .HasColumnName("Duration");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("TrackName", "mousse.Domain.Playlists.Tracks.Track.TrackName#TrackName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("TrackName");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("mousse.Domain.Tags.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("TagName", "mousse.Domain.Tags.Tag.TagName#TagName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("TagName");
                        });

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("mousse.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LikedPlaylistId")
                        .HasColumnType("uuid");

                    b.ComplexProperty<Dictionary<string, object>>("Email", "mousse.Domain.Users.User.Email#Email", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Email");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("UserName", "mousse.Domain.Users.User.UserName#UserName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("UserName");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("LikedPlaylistId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("mousse.Domain.Playlists.Albums.Album", b =>
                {
                    b.HasBaseType("mousse.Domain.Playlists.Playlist");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("mousse.Domain.Playlists.EPs.EP", b =>
                {
                    b.HasBaseType("mousse.Domain.Playlists.Playlist");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("mousse.Domain.Playlists.Singles.Single", b =>
                {
                    b.HasBaseType("mousse.Domain.Playlists.Playlist");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("mousse.Domain.Playlists.UserPlaylists.UserPlaylist", b =>
                {
                    b.HasBaseType("mousse.Domain.Playlists.Playlist");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("PlaylistTrack", b =>
                {
                    b.HasOne("mousse.Domain.Playlists.Playlist", null)
                        .WithMany()
                        .HasForeignKey("PlaylistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mousse.Domain.Playlists.Tracks.Track", null)
                        .WithMany()
                        .HasForeignKey("TracksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TagTrack", b =>
                {
                    b.HasOne("mousse.Domain.Tags.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("mousse.Domain.Playlists.Tracks.Track", null)
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("mousse.Domain.Accesses.Access", b =>
                {
                    b.HasOne("mousse.Domain.Playlists.Playlist", null)
                        .WithMany()
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("mousse.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("mousse.Domain.Followers.Follower", b =>
                {
                    b.HasOne("mousse.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("FollowedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("mousse.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("mousse.Domain.Playlists.Playlist", b =>
                {
                    b.HasOne("mousse.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("mousse.Domain.Users.User", b =>
                {
                    b.HasOne("mousse.Domain.Playlists.UserPlaylists.UserPlaylist", null)
                        .WithOne()
                        .HasForeignKey("mousse.Domain.Users.User", "LikedPlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
